---
title: "Milestone1-Markdown.Rmd"
author: "Yasmin Choma"
date: "2023-11-26"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


LOADING AND PREPROCESSING DATA
```{r}
library(readr)
diabetes <- read_csv("C:/Users/User/github-classroom/BIProject/Milestone 1/data/diabetes.csv")
library(data.table)
setnames(diabetes, old = c("DiabetesPedigreeFunction", "Outcome"), 
         new = c("DPF", "Diagnosis"))
head(diabetes)

dim(diabetes)

sapply(diabetes, class)
```


DATA DISTRIBUTION AND MEASURES
```{r pressure, echo=FALSE}
summary (diabetes)

sapply(diabetes[, c(1, 2, 3, 5, 6, 7, 8, 9)], sd)

sapply(diabetes[, 1:9], var)

library(e1071)
sapply(diabetes[, 1:9],  kurtosis, type = 2)

sapply(diabetes[, 1:9],  skewness, type = 2)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

RELATIONSHIPS AND ASSOCIATIONS
```{r}
diabetes_cov <- cov(diabetes[, 1:9])
View(diabetes_cov)

diabetes_cor <- cor(diabetes[, 1:9])
View(diabetes_cor)
```

VISUALIZATION
```{r}
par(mfrow = c(1, 8))
for (i in 1:8) {
  boxplot(diabetes[, i], main = names(diabetes)[i])
}

library(Amelia)
missmap(diabetes, col = c("red", "grey"), legend = TRUE)

library("corrplot")
corrplot(cor(diabetes[, 1:8]), method = "circle")

```

